### ISSUE TITLE
Substitutes for the mosfets

### ISSUE THREAD

**Issue by Denny-89** [harlock974/time-signal#1]
Hello!

Are [IRF3708](https://www.infineon.com/cms/en/product/power/mosfet/n-channel/irf3708/) and [NDP6020P](https://www.onsemi.com/pdf/datasheet/ndp6020p-d.pdf) a good replacement for BS270 and BS250? I'm asking because those are kinda hard to get here where i live - most cheap ones from Ebay/Aliexpress are counterfeit (relabeled 2N7000 which supports max 200mA or outright non-working) and the postage from reputable sellers like Farnell or Mouser is way too expensive. I still ordered some, but no idea what exactly i'll get...that's why i'm asking if those i already have at home are ok too. In case it's important - my ferrite antenna is 1.24mH 2Ω (desoldered from an Arduino DCF77 receiver module) and the capacitor 3400pF.

Thank you in advance.

Denny

**Comment by harlock974** [comment]
Hello Denny
Sorry for the delay to answer. Your replacement parts seem fine. Let me know if it works.
Regards
Pierre

**Comment by Denny-89** [comment]
Sorry for the late reply, my email client threw Github's notification into spam. The replacement mosfets work and i get the correct frequency and shape on the oscilloscope, but it looks like my cheap wall clock doesn't like the signal (i'm actually using your amplifier circuit in combination with ESP8266-NTP2DCF77). I'll solder everything on a perfboard and try again in case the breadboard jumper wires were too long and/or there was poor contact with the thin antenna wires.

By the way, please correct me if i am wrong - since i managed to find a 332 ceramic disc capacitor with such a horrible tolerance that [the value](https://i.ibb.co/Cbpb4bL/cap.jpg) is actually what i need and the mosfets can handle tens of amps, can i omit the 100nf capacitor and 10ohm resistor?

**Comment by harlock974** [comment]
Hi Denny,
You can omit the 10 ohms resistor. The 100nf helps to clean up the signal. Check with your scope if it made any difference if you remove it.
Did you connect the pin marked as GPIO4 in my schematic to the 620 / 68 ohm pair from NTP2DCF77 output ?

**Comment by Denny-89** [comment]
Thanks for your reply. Yes, i connected it to D2/D8 with the resistors. If i remove the 100nF capacitor, the signal actually looks a little better (a 77.4-77.8kHz square wave with max at 5V that pulsates each second), with the cap it's a little rounded. 

I'll try to find another DCF77 clock to try because i suspect this one is faulty (i am 600km away from the German DCF77 antenna and it still needs almost a month to set DST time; that's the reason why i am building a transmitter). Well, it was 10€, you get what you paid for...

**Comment by Denny-89** [comment]
I kinda gave up on the whole project (for now) since i couldn't get hold of another DCF77 clock with a different mechanism. Seems like everyone i know has the same Lidl store clock with the same issues.

Maybe it will be helpful for someone in the future:
- The ferrite antenna i used is from a [DCF77 receiver module with the label "RC8000"](https://i.ibb.co/nRLnMzg/dcf77-rc8000.png) that is all over Aliexpress and Ebay for around 2-3 euros or US dollars. The C1 smd ceramic capacitor is on the module's pcb parallel to the antenna and its measured value is ~3100pF (probably 3000pF or 3300pF because 3100pF isn't standardized). The antenna's measured inductance is 1.24mH and impedance 2Ω. Sure my measured values could be off since i own just one tester (Fnirsi DSO-TC3) and have no clue how accurate it is.
- You can use this calculator to find the capacitor value - https://www.omnicalculator.com/physics/resonant-frequency-lc
- Stay away from Ebay/Aliexpress ceramic disc capacitor kits because 99% of them don't match their values (100nF is around 40nF for example). I wasted 2h with measuring a thousand of them and got kinda lucky to find the one i needed.
- Watch out for counterfeit mosfets. All BS270 ones i ordered from four different sellers were actually relabeled 2N7000 and it can be noticed by the different pinout (SGD instead of DGS). I got refunds, but still wasted a month of waiting for deliveries.

Sure this stuff is kinda redundant for most experienced electronics people that probably have a whole workshop full of the correct components, but maybe it will help someone.

**Comment by harlock974** [comment]
I also have bad results with an Aliexpress DCF77 module, which struggles to get time above 3 meters from the receiver. To be honest I still don't know if the culprit is the receiver itself or the Arduino decoder program SyncProvider.ino from Thijs Elenbaas.
My other receivers work well at ~ 10 meters distance : a Casio G-Shock GW-5500 and two weather station LaCrosse WS-7014U-IT and Daewoo DWS-62.
